Repository Nosto/nosto-php-sdk, pull requests merged in 2019-01, with the labels that each got.

#154 Add pull request template
  .github/pull-request-template.md
Labels: enhancement

#158 Hotfix/phpdotenv magento2.3
  .github/pull-request-template.md
  CHANGELOG.md
  composer.json
Labels: bug

#159 Add suport for http 2 responses
  src/Request/Http/HttpResponse.php
  tests/unit/HttpResponseTest.php
Labels: bug

#161 Refactor test cases
  tests/_support/MockAccount.php
  tests/_support/MockBilling.php
  tests/_support/MockBuyer.php
  tests/_support/MockCategory.php
  tests/_support/MockCustomer.php
  tests/_support/MockExchangeRate.php
  tests/_support/MockHttpResponse.php
  tests/_support/MockIframe.php
  tests/_support/MockLineItem.php
  tests/_support/MockOAuth.php
  tests/_support/MockOrder.php
  tests/_support/MockOrderStatus.php
  tests/_support/MockOwner.php
  tests/_support/MockPerson.php
  tests/_support/MockProduct.php
  tests/_support/MockProductWithSku.php
  tests/_support/MockPseudoItem.php
  tests/_support/MockSettings.php
  tests/_support/MockSignup.php
  tests/_support/MockSku.php
  tests/_support/MockUser.php
  tests/_support/MockVariation.php
  tests/unit/AccountTest.php
  tests/unit/Helper/DateHelperTest.php
  tests/unit/Helper/HtmlMarkupSerializationHelperTest.php
  tests/unit/Helper/OAuthHelperTest.php
  tests/unit/Helper/PriceHelperTest.php
  tests/unit/Helper/SerializationHelperTest.php
  tests/unit/HistoryExportTest.php
  tests/unit/HttpRequestTest.php
  tests/unit/HttpResponseTest.php
  tests/unit/IFrame/IframeAuthTest.php
  tests/unit/NostoTest.php
  tests/unit/Object/BuyerTest.php
  tests/unit/Object/Email/ImageUrlTest.php
  tests/unit/Object/VariationTest.php
  tests/unit/Operation/AccountTest.php
  tests/unit/Operation/ExchangeRateTest.php
  tests/unit/Operation/OauthSyncTest.php
  tests/unit/Operation/OrderConfirmationTest.php
  tests/unit/Operation/ProductTest.php
  tests/unit/Operation/SSOTest.php
  tests/unit/Operation/SettingsTest.php
  tests/unit/Operation/UninstallTest.php
  tests/unit/Result/GraphqlResultTest.php
  tests/unit/Service/FeatureAccessTest.php
Labels: Refactoring

#162 Hotfix/Bump Phan Version and Vendor
  CHANGELOG.md
  composer.json
  composer.lock
  src/Helper/ExportHelper.php
  src/Helper/IframeHelper.php
  src/Helper/PriceHelper.php
  src/Helper/ValidationHelper.php
  src/Object/Category.php
  src/Object/Email/ImageUrl.php
  src/Object/Notification.php
  src/Object/Settings.php
  src/Operation/AbstractOperation.php
  tests/unit/Helper/HtmlMarkupSerializationHelperTest.php
Labels: enhancement

#164 Add assertion for error message params
  tests/unit/IFrame/IframeAuthTest.php
Labels: enhancement

#167 Add test for special character serialization
  tests/unit/Helper/HtmlMarkupSerializationHelperTest.php
  tests/unit/Helper/SerializationHelperTest.php
Labels: enhancement

#168 Refactor error throwing in PHP SDK
  src/Exception/Builder.php
  src/Nosto.php
  src/Operation/AbstractOperation.php
  src/Operation/InitiateSso.php
  src/Operation/OAuth/AuthorizationCode.php
  src/Operation/OAuth/ExchangeTokens.php
  src/Operation/Recommendation/AbstractOperation.php
  tests/unit/NostoTest.php
Labels: Refactoring

#171 Fix double encoding for oauth redirect URLs
  CHANGELOG.md
  src/Helper/OAuthHelper.php
  src/Operation/OAuth/AuthorizationCode.php
  tests/unit/Helper/OAuthHelperTest.php
Labels: bug
