Repository Nosto/nosto-php-sdk, pull requests merged in 2019-03, with the labels that each got.

#187 Add tags values as constants
  src/Object/Product/Product.php
Labels: enhancement

#196 Add APPS token to the default tokens when creating Nosto Account
  src/Helper/HtmlMarkupSerializationHelper.php
  src/Mixins/HtmlEncoderTrait.php
  src/Object/Signup/Signup.php
Labels: enhancement

#194 Update Jenkinsfile
  CHANGELOG.md
  Jenkinsfile
Labels: bug, enhancement

#201 Bump dockerfile PHP image
  Dockerfile
Labels: bug

#199 Hotfix/fix graphql base url
  CHANGELOG.md
  src/Nosto.php
Labels: bug
